# Generated by Django 5.0 on 2024-01-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_watchlist_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.CharField(default='https://www.gasso.com/wp-content/uploads/2017/04/noimage.jpg', max_length=200, null=True),
        ),
    ]
